name: Ruby Gem

on:
  release:
    types: [created]

jobs:
  build:
    name: build + publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: set up ruby 3.1.x
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 3.1.x

    - name: update version file
      run: |
        echo "# frozen_string_literal: true

        module RbSnake
          VERSION = '${{ github.event.release.name }}'
        end" > lib/rb_snake/version.rb

    - uses: stefanzweifel/git-auto-commit-action@v4
      name: auto commit action
      with:
        skip_fetch: false
        branch: main
        commit_message: Bump version to ${{ github.event.release.name }}

    - name: Publish to RubyGems
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        gem build *.gemspec
        gem push *.gem
      env:
        GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_AUTH_TOKEN}}"
