name: Linter
on: [pull_request]
jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v1

      - name: install ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2

      - name: run rubocop
        uses: reviewdog/action-rubocop@v2
        with:
          rubocop_version: gemfile
          rubocop_extensions: rubocop-rspec:gemfile
