name: Tests
on: [pull_request]
jobs:
  rspec:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: install ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2

      - name: install system dependencies
        run:  sudo apt install -y libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev

      - name: bundle install
        run: |
          gem install bundler
          bundle
      - name: run rspec
        run: rspec
